version: "3.7"

services:
   server:
      build:
         context: .
         dockerfile: Dockerfile
      command: sh -c "npm run migration_up && npm start"
      ports:
         - 80:80
      depends_on:
         - poe_db
      networks:
         - app-network
      volumes:
         - /etc/letsencrypt/:/etc/letsencrypt/

   poe_db:
      container_name: db
      ports:
         - "4000:5432"
      environment:
         - POSTGRES_PASSWORD=
         - POSTGRES_USER=
         - POSTGRES_DB=
      image: postgres:15.4
      volumes:
         - dbdata:/data/db
      networks:
         - app-network

networks:
   app-network:
      driver: bridge

volumes:
   dbdata:
